# Generated by Django 5.0.6 on 2024-06-23 20:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('idCategoriaProducto', models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='Id de Categoria de Producto')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Tipo de Producto')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion de Categoria de Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='Id Producto')),
                ('nombreProducto', models.CharField(max_length=50, verbose_name='Nombre del Producto')),
                ('marca', models.CharField(max_length=40, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=40, verbose_name='Modelo')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio')),
                ('descripcion', models.CharField(default='Sin descripción', max_length=200, verbose_name='Descripcion de Producto')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes', verbose_name='Imagen')),
                ('categoria_producto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.categoriaproducto', verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.producto')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad en stock')),
            ],
        ),
    ]
