# Generated by Django 5.0.6 on 2024-06-23 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240623_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaproducto',
            name='idCategoriaProducto',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Categoria de Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriaproducto', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idProducto',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id Producto'),
        ),
    ]
