# Generated by Django 5.0.6 on 2024-06-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_categoriaproducto_idcategoriaproducto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='Sin descripción', max_length=2000, verbose_name='Descripcion de Producto'),
        ),
    ]
